### ISSUE TITLE
train the model using my own images

### ISSUE THREAD

**Issue by yjdqk** [DanJun6737/TransFace#4]
when I trained the model using my own images,how to fix the config.val_targets in the config. I always got the error: stack expects each tensor to be equal size,bot got [3,364,458] at entry 0 and [3,215,317] at entry 1

**Comment by DanJun6737** [comment]
hi @yjdqk 
config.val_targets is used to select the validation set (e.g., config.val_targets = ['lfw', 'cfp_fp', "agedb_30"]) during training.  You can also speed up the training of the model by not using any validation set (e.g., config.val_targets = []). 
When training on your own dataset, please ensure that the input images undergo proper preprocessing (see paper for details). 
Regarding this error, I may need you to provide more details in order to answer it.

**Comment by yjdqk** [comment]
thanks,I have solved the problem by add  transform.Resize()
